[project]
name = "project-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=6.0",
    "fastapi>=0.127.1",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.45",
    "uuid>=1.30",
    "uvicorn>=0.40.0",
]
